<table>
    <tr>
        <th><?php echo __('Name') ?></th>
        <th><?php echo __('SKU') ?></th>
        <th><?php echo __('Price') ?></th>
        <th>&nbsp;</th>
    </tr>

    <?php foreach($block->getPreviousViewedProducts() as $product):

    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $listBlock = $objectManager->get('\Magento\Catalog\Block\Product\ListProduct');
    $addToCartUrl =  $listBlock->getAddToCartUrl($product);
    ?>
    <tr>
        <td><a href="<?php echo $product->getProductUrl() ?>"><?php echo $product->getName() ?></a></td>
        <td><?php echo $product->getSku() ?></td>
        <td><?=$this->helper('Magento\Framework\Pricing\Helper\Data')->currency($product->getFinalPrice(),true,false) ?></td>
        <td>
            <form data-role="tocart-form" action="<?php echo $addToCartUrl; ?>" method="post">
                <?php echo $block->getBlockHtml('formkey')?>
                <button type="submit"
                        title="Add to Cart"
                        class="action tocart primary">
                    <span><?php echo __('Add to cart') ?></span>
                </button>
            </form>
        </td>
    </tr>
<?php endforeach; ?>
</table>


