<table>
    <tr>
        <th><?php echo __('Name') ?></th>
        <th><?php echo __('SKU') ?></th>
        <th><?php echo __('Price') ?></th>
        <th>&nbsp;</th>
    </tr>

    <?php
    foreach ($block->getPreviousViewedProducts() as $product):
        ?>
        <tr>
            <td><a href="<?php echo $product->getProductUrl() ?>"><?php echo $product->getName() ?></a></td>
            <td><?php echo $product->getSku() ?></td>
            <td><?php echo $block->getFormattedPrice($product); ?></td>
            <td>
                <form data-role="tocart-form" action="<?php echo $block->getAddToCartUrl($product); ?>" method="post">
                    <?php echo $block->getBlockHtml('formkey') ?>
                    <button type="submit"
                            title="Add to Cart"
                            class="action tocart primary">
                        <span><?php echo __('Add to cart') ?></span>
                    </button>
                </form>
            </td>
        </tr>
    <?php endforeach; ?>
</table>


